# -*- coding: utf-8 -*-
"""Untitled5.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1nzTL-2V9PQTEA9wUh6lZNFhjJJJMW1BB
"""

from sklearn.linear_model import LogisticRegression
import pandas as pd
import streamlit as st
from sklearn.preprocessing import StandardScaler

st.title("Model Deployment:Logistic Regression")

st.sidebar.header("User Input Features")
def user_input_features():
  passengerid=st.sidebar.number_input("PassengerID")
  pclass=st.sidebar.selectbox("Pclass",(1,2,3))
  name=st.sidebar.text_input("Name")
  sex=st.sidebar.selectbox("Sex",(0,1))
  age=st.sidebar.number_input("Age")
  sibsip=st.sidebar.number_input("Sibsp")
  parch=st.sidebar.number_input('Parch')
  ticket=st.sidebar.text_input("Ticket")
  fare=st.sidebar.number_input("Fare")
  cabin=st.sidebar.text_input('Cabin')
  embarked=st.sidebar.selectbox("Embarked",(0,1,2))

  data={"PassengerId":passengerid,
        "Pclass":pclass,
        "Name":name,
        "Sex":sex,
        "Age":age,
        "SibSp":sibsip,
        "Parch":parch,
        "Ticket":ticket,
        "Fare":fare,
        "Cabin":cabin,
        "Embarked":embarked}

  df=pd.DataFrame(data,index=[0])
  return df

st.subheader("user input features")
df=user_input_features()
st.write(df)

train_data=pd.read_csv(r"C:\Users\HP\Downloads\training_Data2")
X=train_data.drop("Survived",axis=1)
Y=train_data["Survived"]
scal=StandardScaler()
res=scal.fit_transform(X)
X=pd.DataFrame(res,columns=X.columns)
log=LogisticRegression(max_iter=1000)
log.fit(X,Y)

df.drop(["Name","Cabin","Ticket"],axis=1,inplace=True)
res=scal.transform(df)
df=pd.DataFrame(res,columns=df.columns)
predicted=log.predict(df)
predicted_prob=log.predict_proba(df)

st.write( f'The Passenger is Survived'if predicted_prob[0][1]>0.5 else f'The passenger is not Survived')
st.write(predicted_prob)